In [1]:
import numpy as np 
# Input data 
X = np.array( 
    ([2, 9],
    [1, 5],
    [3, 6]), 
    dtype=float 
)
# Output data 
y = np.array( 
    ([92], 
     [86], 
     [89]), 
     dtype=float 
)
# Normalize input data 
X = X / np.amax(X, axis=0) 
# Normalize output data 
y = y / 100
# Sigmoid Function 
def sigmoid(x): 
    return 1 / (1 + np.exp(-x)) 
# Derivative of Sigmoid Function 
def derivatives_sigmoid(x): 
    return x * (1 - x)
# Variable initialization 
epoch = 5                  
lr = 0.1
inputlayer_neurons = 2     
hiddenlayer_neurons = 3    
output_neurons = 1  
wh = np.random.uniform( 
    size=(inputlayer_neurons, hiddenlayer_neurons) 
)
bh = np.random.uniform( 
    size=(1, hiddenlayer_neurons) 
)
wout = np.random.uniform( 
    size=(hiddenlayer_neurons, output_neurons) 
)
bout = np.random.uniform( 
    size=(1, output_neurons) 
)
# Training 
for i in range(epoch):
    hinp1 = np.dot(X, wh) 
    hinp = hinp1 + bh 
    hlayer_act = sigmoid(hinp) 
    outinp1 = np.dot(hlayer_act, wout) 
    outinp = outinp1 + bout 
    output = sigmoid(outinp)
    EO = y - output 
    outgrad = derivatives_sigmoid(output) 
    d_output = EO * outgrad 
    EH = d_output.dot(wout.T) 
    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad
    wout += hlayer_act.T.dot(d_output) * lr 
    wh += X.T.dot(d_hiddenlayer) * lr
    print("----------- Epoch-", i + 1, "Starts -----------") 
    print("Input:") 
    print(X) 
    print("Actual Output:") 
    print(y) 
    print("Predicted Output:") 
    print(output)
    print("----------- Epoch-", i + 1, "Ends -----------") 
    print()

----------- Epoch- 1 Starts -----------
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.88055696]
 [0.87098617]
 [0.88465806]]
----------- Epoch- 1 Ends -----------

----------- Epoch- 2 Starts -----------
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.88061811]
 [0.87104482]
 [0.88471876]]
----------- Epoch- 2 Ends -----------

----------- Epoch- 3 Starts -----------
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.8806789 ]
 [0.87110313]
 [0.88477909]]
----------- Epoch- 3 Ends -----------

----------- Epoch- 4 Starts -----------
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
[[0.88073931]
 [0.87116108]
 [